### ISSUE TITLE
Installation of the extension impossible when using accented characters in user name

### ISSUE THREAD

**Issue by jdemiaux** [specklesystems/speckle-sketchup#62]
Hi,
The installation of the connector is not possible if the name of the user, I used Jérôme, contains some characters (à, é, è, ç ...).
Here are the error messages.

Erreur de chargement du fichier C:/Users/Jérôme/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/main.rb
Error: #<LoadError: cannot load such file -- sqlite3>
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Users/Jérôme/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/accounts.rb:8:in `rescue in <top (required)>'
C:/Users/Jérôme/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/accounts.rb:3:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Users/Jérôme/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/dialog.rb:5:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Users/Jérôme/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/main.rb:4:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2022/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2022/Tools/extensions.rb:197:in `load'
C:/Users/Jérôme/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector.rb:39:in `register_extension'
C:/Users/Jérôme/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector.rb:39:in `<module:SpeckleConnector>'
C:/Users/Jérôme/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector.rb:6:in `<module:SpeckleSystems>'
C:/Users/Jérôme/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector.rb:5:in `<top (required)>'

Regards.

**Comment by oguzhankoral** [comment]
@jdemiaux Thanks for reporting,

This is happening most probably load paths forced to encode "UTF-8". I will check this one out and fix. 

Best,

**Comment by oguzhankoral** [comment]
@jdemiaux Can you please test your case with new release `2.10.0-rc4`? Let me know please if issue is still persist! Hope will work.
![2 10 0-rc4_installer](https://user-images.githubusercontent.com/45078678/203743202-3193299b-789d-4b32-abc2-d387f8f919ff.png)

**Comment by jdemiaux** [comment]
Hi,
Not better.
The installation works well but as soon as I use it, sketchup crashes.
At launch the following messages appear

Erreur de chargement du fichier C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/main.rb
Error: #<LoadError: cannot load such file -- sqlite3>
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/accounts.rb:8:in `rescue in <top (required)>'
C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/accounts.rb:3:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/dialog.rb:5:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Program Files/SketchUp/SketchUp 2022/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/main.rb:4:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2022/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2022/Tools/extensions.rb:197:in `load'
C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector.rb:39:in `register_extension'
C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector.rb:39:in `<module:SpeckleConnector>'
C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector.rb:6:in `<module:SpeckleSystems>'
C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector.rb:5:in `<top (required)>'

Hope this helps

**Comment by oguzhankoral** [comment]
@jdemiaux It seems to me somehow you could not install latest version appropriately. Because error causes from file `main.rb` in `C:/Users/Hélène/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/speckle_connector/main.rb` which we do not have this file anymore with new releases. So your SketchUp tries to run old version.

Can you please uninstall SketchUp connector by `Manager for Speckle` and reinstall `2.10.0`?

**Comment by jdemiaux** [comment]
apology.
Indeed the update was not done correctly.
So I redid a clean installation of the connector 2.10.0.
No more error messages at launch but a bugsplat as soon as I click on the launch connector button.
Works on the same computer with a path without accent.
no pressure, no emergency, I changed the name of the user directory.
Thanks for your work

**Comment by oguzhankoral** [comment]
@jdemiaux Thanks for reporting this issue anyway. This might happen to someone else, I will investigate to fix this one.

**Comment by oguzhankoral** [comment]
@jdemiaux Let me ask you something please to understand encoding problem with more detail. I guess this happens when users not using English version of Windows + encoding with `UTF-8`. Can you confirm me please if your current Windows is not an English version? If not can you provide me with which language you run your Windows?

**Comment by jdemiaux** [comment]
@oguzhankoral French version of windows 10
